#!/bin/sh
# Arguments:
#  $1 - path to pngtest binary

# normal execution
$1/pngtest --strict data/pngtest.png

# various crashers
# using --relaxed because some come from fuzzers that don't maintain CRC's
DATADIR=tests/crashers

$1/pngtest --relaxed ${DATADIR}/badcrc.png
$1/pngtest --relaxed ${DATADIR}/badadler.png
$1/pngtest --xfail ${DATADIR}/bad_iCCP.png
$1/pngtest --xfail ${DATADIR}/empty_ancillary_chunks.png
$1/pngtest --xfail ${DATADIR}/huge_*_chunk.png
$1/pngtest --xfail ${DATADIR}/huge_IDAT.png
